name: resident
description: A new Flutter project.


version: 1.0.0+2

environment:
  sdk: ">=2.15.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

    # Internet connection checker
  internet_connection_checker: ^1.0.0+1
  connectivity: ^3.0.6

  # State Management
  flutter_bloc: ^8.1.3

  # Dependency Injection
  get_it: ^7.6.6


  either_dart: ^1.0.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  new_version: ^0.3.1


  flutter_screenutil: ^5.9.0


    # Widget Library
  flutter_svg: ^2.0.9
  grouped_list: ^5.1.2
  group_list_view: ^1.1.1
  modal_bottom_sheet: ^2.1.2
  infinite_scroll_pagination: ^4.0.0
  percent_indicator: ^4.2.3
  url_launcher: ^6.2.3
  mask_text_input_formatter: ^2.7.0

  flutter_rounded_date_picker: ^3.0.4
  another_flushbar: ^1.12.30
  image_picker: ^1.0.7
  flutter_multi_formatter: ^2.12.4
  cached_network_image: ^3.3.1
  pinput: ^3.0.1
  sms_autofill: ^2.3.0

  #Open PDF in a viewer
  flutter_cached_pdfview: ^0.4.2




  # Data/Domain libraries
  # Dio library for REST API
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0


  firebase_messaging: ^12.0.2
  firebase_core: ^1.20.1
  flutter_local_notifications: ^16.3.0
  local_auth: ^2.1.8
  overlay_support: ^2.1.0


dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  package_info_plus: ^5.0.1
  wakelock_windows: any
  win32: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

  flutter_lints: ^3.0.1

  change_app_package_name: ^1.1.0

  freezed_annotation: ^2.4.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Montserrat-Regular.ttf
          style: normal
          weight: 400
